Task/Task/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Ulvi.Data;
using Ulvi.Models;

namespace Ulvi.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly DataContext _db;
        private readonly UserManager<User> _userManager;
        public HeaderViewComponent(DataContext db, UserManager<User> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio model = _db.Bios.FirstOrDefault();
            ViewBag.User = "";
            if (User.Identity.IsAuthenticated)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                ViewBag.User = user;
            }
            return View(await Task.FromResult(model));
        }
    }
}

Task/Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Academics &mdash; Website by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/jquery-ui.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">

    <link rel="stylesheet" href="~/assets/css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="~/assets/css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="~/assets/fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="~/assets/css/aos.css">
    <link href="css/jquery.mb.YTPlayer.min.css" media="all" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" 
          crossorigin="anonymous">


</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <div class="site-wrap">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>


        <div class="py-2 bg-light">


            @await Component.InvokeAsync("Header")


        </div>
    </div>
    @RenderBody()

   


    <script src="~/assets/js/jquery-3.3.1.min.js"></script>
    <script src="~/assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/assets/js/jquery-ui.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.stellar.min.js"></script>
    <script src="~/assets/js/jquery.countdown.min.js"></script>
    <script src="~/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="~/assets/js/jquery.easing.1.3.js"></script>
    <script src="~/assets/js/aos.js"></script>
    <script src="~/assets/js/jquery.fancybox.min.js"></script>
    <script src="~/assets/js/jquery.sticky.js"></script>
    <script src="~/assets/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="~/assets/js/index.js"></script>
    <script src="~/assets/js/main.js"></script>

</body>

</html>